# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b71cb0d2cbc2c2212770d155e239e16330b46fda87ccd60576b59057627e4d4c11e7ef6955238c2e751e993e56c24783c52e65e41e0b9d49d2c310e1c62d8b02

test:
  secret_key_base: bfae7638fba8ea84c115491551769cce8831302da05b0879da0082d94447a30ebec608c6172aa3363fd9d9dfc751cc5206b601f95dd6af2554813719783966e0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
